{
  "general": {
    "userAgentRegexes": [],
    "replaceStrings": [],
    "publicKey": "zpzzwmb",
    "deviceRegKey": "brf1tmrd6e826ez2vet26ba39c",
    "appName": "seeLL",
    "initialUrl": "https://onev2.seellbr.com",
    "keepScreenOn": null,
    "screenOrientation": {
      "iphone": null,
      "ipad": null,
      "androidPhone": null,
      "androidTablet": null
    },
    "enableWindowOpen": true,
    "userAgentAdd": "median",
    "forceUserAgent": "",
    "iosUserAgentAdd": "median",
    "iosForceUserAgent": "",
    "androidUserAgentAdd": "median",
    "androidForceUserAgent": "",
    "languages": [],
    "nativeBridgeUrls": [],
    "iosBundleId": "co.median.ios.zpzzwmb",
    "androidPackageName": "co.median.android.zpzzwmb",
    "androidSigningKey": "release",
    "iosCustomHeaders": {},
    "androidCustomHeaders": {},
    "injectMedianJS": true,
    "forceSessionCookieExpiry": 0
  },
  "navigation": {
    "ignorePageFinishedRegexes": [],
    "redirects": [],
    "iosSettings": {},
    "iosPullToRefresh": true,
    "androidPullToRefresh": false,
    "swipeGestures": null,
    "iosConnectionOfflineTime": 10,
    "androidConnectionOfflineTime": 10,
    "regexInternalExternal": {
      "active": true,
      "rules": [
        {
          "id": 1,
          "mode": "external",
          "label": "Non-web links",
          "pagesToTrigger": "custom",
          "regex": "^(?!https?://).*"
        },
        {
          "id": 2,
          "mode": "appbrowser",
          "label": "Facebook",
          "pagesToTrigger": "custom",
          "regex": "https?://([-\\w]+\\.)*facebook\\.com.*"
        },
        {
          "id": 3,
          "mode": "appbrowser",
          "label": "Twitter/X",
          "pagesToTrigger": "custom",
          "regex": "https?://([\\-\\w]+\\.)*(twitter|x)\\.com/.*"
        },
        {
          "id": 4,
          "mode": "appbrowser",
          "label": "Instagram",
          "pagesToTrigger": "custom",
          "regex": "https?://([-\\w]+\\.)*instagram\\.com/.*"
        },
        {
          "id": 5,
          "mode": "appbrowser",
          "label": "Google Maps",
          "pagesToTrigger": "custom",
          "regex": "https?://maps\\.google\\.com.*"
        },
        {
          "id": 6,
          "mode": "appbrowser",
          "label": "Google Maps Search",
          "pagesToTrigger": "custom",
          "regex": "https?://([-\\w]+\\.)*google\\.com/maps/search/.*"
        },
        {
          "id": 7,
          "mode": "appbrowser",
          "label": "LinkedIn",
          "pagesToTrigger": "custom",
          "regex": "https?://([-\\w]+\\.)*linkedin\\.com/.*"
        },
        {
          "id": 8,
          "mode": "internal",
          "label": "Microsoft Login",
          "pagesToTrigger": "custom",
          "regex": "https?://login\\.microsoftonline\\.com.*"
        },
        {
          "id": 9,
          "mode": "internal",
          "label": "All pages on my domain",
          "pagesToTrigger": "domain",
          "regex": "https?:\\/\\/([-\\w]+\\.)*seellbr.com(\\/.*)?$"
        },
        {
          "id": 10,
          "mode": "appbrowser",
          "label": "All Other Links",
          "pagesToTrigger": "all",
          "regex": ".*"
        }
      ]
    },
    "deepLinkDomains": {
      "enableAndroidApplinks": false,
      "domains": []
    },
    "navigationTitles": {
      "active": true,
      "titles": []
    },
    "iosShowRefreshButton": false,
    "androidShowRefreshButton": false,
    "actionConfig": {
      "active": true,
      "actions": [],
      "actionSelection": []
    },
    "navigationLevels": {
      "active": true,
      "levels": []
    },
    "sidebarNavigation": {
      "menuSelectionConfig": {
        "redirectLocations": [
          {
            "regex": ".*",
            "menuName": "default",
            "loggedIn": true
          }
        ]
      },
      "menus": [
        {
          "active": false,
          "items": [
            {
              "url": "https://onev2.seellbr.com/maintenance.html",
              "label": "Voltar para página de manutenção",
              "subLinks": []
            }
          ],
          "name": "default"
        }
      ]
    },
    "tabNavigation": {
      "active": false,
      "tabMenus": [],
      "tabSelectionConfig": []
    },
    "androidShowOfflinePage": true,
    "iosShowOfflinePage": true,
    "toolbarNavigation": {
      "enabled": false,
      "visibilityByPages": "allPages",
      "visibilityByBackButton": "backButtonActive",
      "regexes": [
        {
          "enabled": true,
          "regex": ".*"
        }
      ],
      "items": [
        {
          "system": "back",
          "titleType": "defaultText",
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        },
        {
          "system": "refresh",
          "enabled": false,
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        },
        {
          "system": "forward",
          "enabled": false,
          "titleType": "defaultText",
          "visibility": "allPages",
          "urlRegex": [
            {
              "enabled": true,
              "regex": ".*"
            }
          ]
        }
      ]
    },
    "maxWindows": {
      "enabled": false,
      "numWindows": 5,
      "autoClose": false
    }
  },
  "styling": {
    "splashScreen": {
      "ios": {
        "backgroundImage": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142336_wbud7azbv1u26_FFFFFF_1_2x2.png",
        "backgroundImageDark": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142344_2d7559189q5ew_000000_1_2x2.png",
        "backgroundColor": "#FFFFFF",
        "backgroundColorDark": "#000000",
        "centerImage": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
        "centerImageDark": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
        "animation": null,
        "animationDark": null,
        "animationFrame": null,
        "animationFrameDark": null,
        "animationLoop": "once",
        "animated": false
      },
      "android": {
        "launchImages": {
          "mdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142458_a2z0t3bphu6g8_180x180.png",
          "hdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142465_bka2vbpq4ktuc_270x270.png",
          "xhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142469_91ucunebcm86r_360x360.png",
          "xxhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142473_11h6md3acykbw_540x540.png",
          "xxxhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142479_7jhtt0qnr8ury_720x720.png"
        },
        "launchImagesDark": {
          "mdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142488_2q1yje9we57gg_180x180.png",
          "hdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142493_e89w6hrux2f5y_270x270.png",
          "xhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142502_a1mna2wh8amb8_360x360.png",
          "xxhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142510_291jn1yn2tptw_540x540.png",
          "xxxhdpi": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/1755466142520_g7mt57ywg2qbe_720x720.png"
        },
        "showSplash": true,
        "backgroundColor": "#FFFFFF",
        "backgroundColorDark": "#000000",
        "animation": null,
        "animationDark": null,
        "animationFrame": null,
        "animationFrameDark": null,
        "animationLoop": "once",
        "animated": false
      }
    },
    "transitionInteractiveDelayMax": 0.2,
    "menuAnimationDuration": 0.15,
    "iosTheme": "default",
    "androidTabPressedBackgroundColor": "#CCCCCC",
    "androidTabPressedBackgroundColorDark": "#999999",
    "androidBackgroundColor": "#FFFFFF",
    "androidBackgroundColorDark": "#333333",
    "icon": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "iosIcon": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "customIcons": {},
    "iosDarkMode": "auto",
    "iosEnableBlurInStatusBar": false,
    "iosStatusBarStyle": "auto",
    "iosEnableOverlayInStatusBar": false,
    "iosStatusBarBackgroundColor": "#ffffffff",
    "iosStatusBarBackgroundColorDark": "#000000",
    "androidStatusBarStyle": "auto",
    "androidEnableOverlayInStatusBar": false,
    "androidStatusBarBackgroundColor": "#ffffff",
    "androidStatusBarBackgroundColorDark": "#333333",
    "iosTintColor": "#0E0D08",
    "iosTintColorDark": "#ffffff",
    "androidIcon": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "androidTheme": "auto",
    "androidAccentColor": "#0E0D08",
    "androidAccentColorDark": "#ffffff",
    "androidSystemNavBarColor": "#FFFFFF",
    "androidSystemNavBarColorDark": "#000000",
    "androidPullToRefreshColor": "#1A100B",
    "androidPullToRefreshColorDark": "#FFFFFF",
    "iosActivityIndicatorColor": "#808080",
    "iosActivityIndicatorColorDark": "#808080",
    "androidActivityIndicatorColor": "#808080",
    "androidActivityIndicatorColorDark": "#808080",
    "androidWebviewTextZoom": null,
    "hideWebviewAlpha": 0.5,
    "forceViewportWidth": null,
    "pinchToZoom": null,
    "iosDynamicType": null,
    "androidSwipeNavigationBackgroundColor": "#FFFFFF",
    "androidSwipeNavigationBackgroundColorDark": "#333333",
    "androidSwipeNavigationActiveColor": "#000000",
    "androidSwipeNavigationActiveColorDark": "#FFFFFF",
    "androidSwipeNavigationInactiveColor": "#666666",
    "androidSwipeNavigationInactiveColorDark": "#666666",
    "navigationTitleImageLocation": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "navigationTitleImageLocationDark": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "iosTitleColor": "#0E0D08",
    "iosTitleColorDark": "#ffffff",
    "iosNavigationBarTintColor": "#f8f8f8",
    "iosNavigationBarTintColorDark": "#202020",
    "androidActionBarBackgroundColor": "#FFFFFF",
    "androidActionBarBackgroundColorDark": "#333333",
    "androidHeaderImage": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "androidHeaderImageDark": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "androidActionBarForegroundColor": "#1A100B",
    "androidActionBarForegroundColorDark": "#FFFFFF",
    "iosSidebarBackgroundColor": "#f8f8f8",
    "iosSidebarBackgroundColorDark": "#202020",
    "iosSidebarFont": "Default",
    "iosHeaderImage": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "iosHeaderImageDark": "https://gonativeio.s3.amazonaws.com/app_files/zpzzwmb/app_icon.png",
    "iosSidebarTextColor": "#0E0D08",
    "iosSidebarTextColorDark": "#ffffff",
    "androidSidebarBackgroundColor": "#FFFFFF",
    "androidSidebarBackgroundColorDark": "#333333",
    "androidSidebarForegroundColor": "#1A100B",
    "androidSidebarForegroundColorDark": "#FFFFFF",
    "androidSidebarSeparatorColor": "#CCCCCC",
    "androidSidebarSeparatorColorDark": "#666666",
    "androidSidebarHighlightColor": "#1A100B",
    "androidSidebarHighlightColorDark": "#FFFFFF",
    "androidShowLogoInSideBar": true,
    "androidShowAppNameInSideBar": true,
    "androidTabBarBackgroundColor": "#FFFFFF",
    "androidTabBarBackgroundColorDark": "#333333",
    "androidTabBarTextColor": "#949494",
    "androidTabBarTextColorDark": "#FFFFFF",
    "androidTabBarIndicatorColor": "#1A100B",
    "androidTabBarIndicatorColorDark": "#666666",
    "iosTabBarTintColor": "#f8f8f8",
    "iosTabBarTintColorDark": "#000000",
    "iosTabBarInactiveColor": "#A1A1A1",
    "iosTabBarInactiveColorDark": "#818181",
    "disableAnimations": false,
    "navigationTitleImage": false,
    "androidHideTitleInActionBar": false,
    "showNavigationBar": false,
    "showActionBar": false
  },
  "allowZoom": null,
  "contextMenu": {
    "enabled": false,
    "linkActions": [
      "copyLink",
      "openExternal"
    ]
  },
  "security": {
    "network": {
      "allowInsecure": null
    }
  },
  "permissions": {
    "usesGeolocation": false,
    "iosLocationUsageDescription": "",
    "iosCameraUsageDescription": "",
    "iosMicrophoneUsageDescription": "",
    "enableWebRTCamera": false,
    "enableWebRTCMicrophone": false,
    "androidDownloadToPublicStorage": false,
    "iOSATTUserTrackingDescription": "",
    "iOSRequestATTConsentOnLoad": false
  },
  "developmentTools": {
    "enableWebConsoleLogs": false
  },
  "services": {
    "oneSignalV5": {
      "active": false
    }
  }
