workflows:
  ios-workflow:
    name: Build iOS
    max_build_duration: 60
    environment:
      xcode: latest
      node: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build iOS
        script: |
          cd ios
          pod install
          cd ..
          xcodebuild -workspace ios/YourApp.xcworkspace \
            -scheme YourApp \
            -sdk iphoneos \
            -configuration Release archive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/YourApp.xcarchive
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        apple_id: $APPLE_ID
        password: $APP_SPECIFIC_PASSWORD
