workflows:
  build-ipa:
    name: Build iOS .ipa
    max_build_duration: 60
    environment:
      xcode: latest
    scripts:
      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..
      - name: Build IPA
        script: |
          xcodebuild \
            -workspace ios/seeLL.xcworkspace \
            -scheme seeLL \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $HOME/Library/Developer/Xcode/Archives/seeLL.xcarchive archive

          xcodebuild \
            -exportArchive \
            -archivePath $HOME/Library/Developer/Xcode/Archives/seeLL.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
